#+TITLE:       About
#+AUTHOR:      Tim Hawes
#+EMAIL:       tim@selfdidactic.com
#+DATE:        2015-06-09 Tue
#+CATEGORY: Education
#+TAGS: Henry Adams
#+TAGS: Education
#+begin_src
"Nothing in education is so astonishing as the amount of ignorance it
accumulates in the form of inert facts."

Henry Adams - The Education
#+end_src


Even after graduating with honors from Harvard University, and going on to
graduate school in Munich, Germany, Henry Adams recognized the impotency of the
popular education system of his day. Nothing has changed, in regards to
education, since his time. We still adhere to a "Prussian" style of education,
from our first day of kindergarten on through to graduate school. Seldom are we
taught how to think critically or analytically, but rather, much like the old
Soviet disinformatia, we are told what to think.

This sort of education prepares one for only one thing, servitude. As long as we
accept this education uncritically, it is very unlikely to change. Slaves are
kept under control by limiting their education. It used to be frowned upon to
teach slaves how to read in this country. If you do have literate slaves, then
you will be inclined to try and keep them ignorant in other ways. This is the
purpose of "state education".

The truth of the matter is that education really is something we all should be
investing in continually, long after graduation. Having a wife with many long
chronic illnesses, and having to see, sometimes, as many as twenty different
doctors every year, I have come to appreciate the value a doctor might place in
furthering their education. The ones who do not, become little more than
complacent and ineffectual.

Self Didactic means "self taught". This site is not in any way a political think
tank, or action group to resist the state. If you want to do that, then I highly
recommend gettng involved with home schooling. Regardless how you feel about
statism and liberty, you can benifit greatly from this site. On one condition,
of course. That you are committed to your own self education.
