#+TITLE:       Self Didactic Part II
#+AUTHOR:      Tim Hawes
#+EMAIL:       tim@selfdidactic.com
#+DATE:        2009-06-28 Sun
#+CATEGORY: Education

In spite of all my 'un-disciplined' characteristics, I have learned to be very
disciplined in other ways.

Nearly twenty years ago, I took a third-shift security job, for two
years. During that time, I gave myself a liberal arts education. I read Plato,
Aristotle, Sophocles, Augustine, John Calvin, and Cornelius Van Til. I read
Christian theology, secular and Church history, and even Karl Marx, Bertrand
Russel, and Earnest Hemingway. I worked five nights a week, and on my nights
off, I took the bus to a 24 hour breakfast restaurant, and read all night there.

This is an education I am very happy I got. And one I seek to continue. I do not
have any of the time I used to have when I was younger, but I still have
time. Helping others do this is what this site is all about. You may not be the
least bit interested in philosophy or theology, but you should be. These are not
abstract topics that have no basis in reality. No, but these topics exist
because man knows he strives to gain his purpose on this earth. Purpose is what
our existence presupposes, and deep down in our heart of hearts, we know this.

Herman Dooyeweerd once put it very succinctly, "meaning precedes essence". Now,
I cannot tell you your purpose in such a way that you would cling to it and make
it the passion of your life at every waking hour. There is a simple answer to
this question, but it is the business of most people to suppress this truth in
rebellion against Yahweh.

That being said, yes, I did say Yahweh, and not Atman, or Budha, or Allah. And I
did not say Y*HW*H, so that would exclude Judaism as well. I am unashamedly
Christian. I did not say that to start any arguments or to offend any one else's
religion. However, I do not believe in beating around the bush, and if you are
still around, and have not allowed yourself to be offended by my exclusionary
belief system, you are well on your way to improving your own education. Not
from me, necessarily, but your resolve shows your ability to 'suspend judgment'
as it were, to pick up the many gems of wisdom and knowledge laying on the
ground.

I do not presume the ability to change anyone's mind on anything, and I am not
going to try. But when you believe you have found your purpose for life, I can
help you in getting there. "Getting there" involving your own self education.

Perhaps this involves learning logic, or learning a foreign language or learning
a musical instrument. In any case, in doing these things, it is merely a matter
of finding good material to read, and a schedule to read, and practice your new
topic. From there, its just sticking to it consistently that will carry you
through.
